server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# user-service 커스텀 설정
user:
  greeting: "안녕! 설정 바꿨어!"
  max-users: 999
